### ISSUE TITLE
Questions regarding network architecture

### ISSUE THREAD

**Issue by convolutionalJellyfish** [DanielTakeshi/deformable-ravens#12]
Hello Dr Seita,

First of all, thank you for making the code for your paper publicly available, and for the contribution your work has brought to the research community.
I have been reading the "goal-conditioned transporter network" paper in detail, and have a few points of confusion I was hoping I could ask about:

1. **For Transporter-Goal-Stack**: Although Fig 3 of the paper seems to imply that only $o_t$ is input to $\Phi_{query}$ and $\Phi_{key}$, I was reading through the code and noticed that it seems that actually the full stacked $(o_t, o_g)$ is used as the input to these two FCNs (not only as the input to $f_{pick}$). Could you please confirm this point? [link](https://github.com/DanielTakeshi/deformable-ravens/blob/be4917cae80207f37f04530d864effd892aa3db4/ravens/agents/transporter.py#L506)
2. **For Transporter-Goal-Split:** Similarly, although Fig 3 of the paper seems to imply that only $o_t$ is input to $f_{pick}$ in this architecture, from the code it seems that actually the full stacked $(o_t, o_g)$ is used as input. Could you please confirm this point? [link](https://github.com/DanielTakeshi/deformable-ravens/blob/be4917cae80207f37f04530d864effd892aa3db4/ravens/agents/transporter.py#L445-L446)
(It seems I may be having some misunderstandings regarding how to read Fig 3 properly, so please do let me know if this is the case.)
3. From the code it seems that rotations are actually performed (although not shown in Fig 3). My understanding is that (some input image of some size) is input to $\Phi_{query}$ and we get dense features as output from this; then $T_{pick}$ is sampled from $Q_{pick}$, and then we create rotated crops from the extracted dense features, around $T_{pick}$. We then convolve each crop to get $T_{place}$ as the location with maximum placing success, calculated over all locations and over all rotations. Is this correct?
4. Related to the previous question. Is it correct to understand $Q_{place}$ as a set of `num_rotations` maps where each map is associated with a rotation, and the pixel values in the map are correlated with predicted placement success given this pick and rotation?

I'm sorry for so many questions but I would really like to better understand the paper's details.
Thank you very much for your time!

**Comment by DanielTakeshi** [comment]
@convolutionalJellyfish thanks for the questions!  Quick answers:

1. To clarify, Figure 3 shows Transporter-Goal-Split (not the stack variant). The stacked variant uses input with current observation and goal observation to all networks.

2. To clarify, this is only for the attention module. Not the transport module, which is the more interesting part of this.

3. Rotations are available in the code but I found that it wasn't helpful for these deformable manipulation tasks. For example, rotating while also doing pick-and-place for cloth usually leads to really bad cloth physics. So I didn't use them for the tasks in the paper but the original ravens benchmark (with the original Transporter network)  uses rotation.

**Comment by convolutionalJellyfish** [comment]
@DanielTakeshi Hello Dr Seita,

Thank you so much for the response! I really appreciate it and understand Fig 3 much better now. Indeed I was misreading it :-)

Regarding 2, then do I understand correctly that the Attention module is the same between Goal-Split and Goal-Stack? Namely, it takes $(o_t, o_g)$ as input for both.

Regarding 3, then do I understand correctly that this means the dimensionality of $Q_{place}$ is just `H x W x 1` (rather than `H x W x num_rotations`) in the goal-conditioned networks used? Since there are no rotations?

Regarding 3 again: I was thinking there would be rotations because the pseudocode in Appendix IV has rotations. And so does the code here for each architecture type:
* (Goal-Split):

https://github.com/DanielTakeshi/deformable-ravens/blob/6ff2443ba7f6673ba4696484e052441262cc14d7/ravens/models/transport_goal.py#L96

* (Goal-Stack):

https://github.com/DanielTakeshi/deformable-ravens/blob/6ff2443ba7f6673ba4696484e052441262cc14d7/ravens/models/transport.py#L113

If there are no rotations used for the tasks in the paper, could you please clarify what this code corresponds to?

Thank you very much again for your time and helping me better understand your work!

**Comment by DanielTakeshi** [comment]
> Regarding 2, then do I understand correctly that the Attention module is the same between Goal-Split and Goal-Stack? Namely, it takes $(o_t, o_g)$ as input for both.

Yes

> Regarding 3, then do I understand correctly that this means the dimensionality of $Q_{place}$ is just `H x W x 1` (rather than `H x W x num_rotations`) in the goal-conditioned networks used? Since there are no rotations?
> 
> Regarding 3 again: Thank you--that explains why rotations are not shown in Fig 3! However I was thinking there would be rotations because the pseudocode in Appendix IV has rotations. And so does the code here for each architecture type:

I think during the code, we _allow_ for more rotations if needed. However, the _training data_ will not employ any rotations other than the identity one, so the network should simply not no

Disclaimer: I haven't worked with the code recently so my memory is fuzzy on this (and currently consumed with some other work so can't put too much time into verifying this) but this seems reasonable to me. 

Also if you want a visual of how GCTN works I have some more visuals in this public video of me giving a talk, see around 27 minutes into the video https://www.youtube.com/watch?v=cGJ9zIGeYLs&t=1s

**Comment by convolutionalJellyfish** [comment]
@DanielTakeshi Hello Dr Seita,

Thank you so much for the quick response!!! 

Regarding the rotations: I looked at the code in the direction you pointed. 
Here is what I found: it seems that for training, `num_rots` (with default 24) is used:
https://github.com/DanielTakeshi/deformable-ravens/blob/be4917cae80207f37f04530d864effd892aa3db4/bash/train_bag-color-goal.sh#L4
https://github.com/DanielTakeshi/deformable-ravens/blob/6ff2443ba7f6673ba4696484e052441262cc14d7/main.py#L205
while for inference, `num_rots_inf` (with value 1) is used:
https://github.com/DanielTakeshi/deformable-ravens/blob/be4917cae80207f37f04530d864effd892aa3db4/bash/load_bag-color-goal.sh#L4-L8

so I guess from this we can understand that although the network was trained with 24 rotation options, it was restricted to 1 rotation option at inference (for the reasons above that you stated). From what you can remember, is this correct?

Regarding the video: Thank you very much for sending it!!! I am sure it will help a lot, and I will study it carefully!

I'm sorry for asking so many detailed questions! I really appreciate the time and effort you have put into answering them!
Thank you very much again!!

**Comment by DanielTakeshi** [comment]
> so I guess from this we can understand that although the network was trained with 24 rotation options, it was restricted to 1 rotation option at inference (for the reasons above that you stated). From what you can remember, is this correct?

Yes, this makes a lot more sense.

**Comment by convolutionalJellyfish** [comment]
I see--I understand then! 

I will close this issue now!
Thank you so much for answering so many of my questions!! It helped me a lot in understanding your work!
I hope you have a great day!!

**Comment by DanielTakeshi** [comment]
You're welcome! If you use GCTN in your paper / project, I'd be happy to read it!
