### ISSUE TITLE
For goal-conditioned task, how does the environment judge that the task is successful?

### ISSUE THREAD

**Issue by ShiguangSun** [DanielTakeshi/deformable-ravens#14]
Hi，
I have a question here. For goal-conditioned tasks, how does the environment judge that the task is successful? Because the inputs of agent are current observation image and goal image. Does the environment judge success by comparing the current observation image with the target image? Or is the environment judge success by comparing particle positions, and the image is only used as input to the agent?

**Comment by DanielTakeshi** [comment]
The success criteria is environment-dependent and based on using the ground truth state information. You might want to look here:

https://github.com/DanielTakeshi/deformable-ravens/blob/be4917cae80207f37f04530d864effd892aa3db4/ravens/tasks/task.py#L1108-L1164

and the code that leads to this.

**Comment by ShiguangSun** [comment]
> The success criteria is environment-dependent and based on using the ground truth state information. You might want to look here:
> 
> https://github.com/DanielTakeshi/deformable-ravens/blob/be4917cae80207f37f04530d864effd892aa3db4/ravens/tasks/task.py#L1108-L1164
> 
> and the code that leads to this.

Thank you very much.
