### ISSUE TITLE
Function of the code 

### ISSUE THREAD

**Issue by 74284853** [DanielTakeshi/deformable-ravens#5]
I want to know the functions of load.py and how to view zone-template.urdf directly in Pybullet , can you tell me,Plase?

**Comment by DanielTakeshi** [comment]
Hi @74284853 ! Can you be a little more precise with your question by letting me know what command you tried?

**Comment by 74284853** [comment]
> Hi @74284853 ! Can you be a little more precise with your question by letting me know what command you tried?

I downloaded the Demonstration Data on the project's website, but I don't know how to use it for testing.I know how to train, can you tell me how to test the network?Thank you!

**Comment by DanielTakeshi** [comment]
To test, you need to make sure you have a trained policy. Then you can use `load.py`. Have you seen my commands document here:

https://github.com/DanielTakeshi/deformable-ravens/blob/master/Commands.md

I believe these commands are exactly what I used for the paper.

**Comment by DanielTakeshi** [comment]
Closing, let me know if you run into further issues.
