### ISSUE TITLE
Error message of python packages(tensorflow package version may have mismatched)

### ISSUE THREAD

**Issue by k-makihara** [DanielTakeshi/deformable-ravens#9]
I created anaconda environment using your instruction in README(install_ubuntu.sh), and try to execute dataset.py.
But some errors of tensorflow packages. If you know the solution, could you share me?
I put the below that the error message when I tried " python ravens/dataset.py --path goals/bag-color-goal/".

Thank you,

> pybullet build time: Sep 22 2020 00:55:20
2021-10-04 18:00:30.592384: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Detected TensorFlow version:  2.4.1
Traceback (most recent call last):
  File "ravens/dataset.py", line 9, in <module>
    from ravens import utils as U
  File "/home/user/deformable-ravens/ravens/__init__.py", line 2, in <module>
    import ravens.agents as agents
  File "/home/user/deformable-ravens/ravens/agents/__init__.py", line 1, in <module>
    from ravens.agents.dummy import DummyAgent
  File "/home/user/deformable-ravens/ravens/agents/dummy.py", line 10, in <module>
    from ravens.models import Attention, Transport
  File "/home/user/deformable-ravens/ravens/models/__init__.py", line 6, in <module>
    from ravens.models.conv_mlp import ConvMLP
  File "/home/user/deformable-ravens/ravens/models/conv_mlp.py", line 5, in <module>
    import tensorflow_hub as hub
  File "/home/user/anaconda3/envs/py3-defs/lib/python3.7/site-packages/tensorflow_hub/__init__.py", line 88, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/home/user/anaconda3/envs/py3-defs/lib/python3.7/site-packages/tensorflow_hub/estimator.py", line 62, in <module>
    class LatestModuleExporter(tf.compat.v1.estimator.Exporter):
  File "/home/user/anaconda3/envs/py3-defs/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/user/anaconda3/envs/py3-defs/lib/python3.7/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/user/anaconda3/envs/py3-defs/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/anaconda3/envs/py3-defs/lib/python3.7/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/user/anaconda3/envs/py3-defs/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 13, in <module>
    from tensorflow_estimator._api.v1.estimator import tpu
  File "/home/user/anaconda3/envs/py3-defs/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/tpu/__init__.py", line 14, in <module>
    from tensorflow_estimator.python.estimator.tpu.tpu_estimator import TPUEstimator
  File "/home/user/anaconda3/envs/py3-defs/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 108, in <module>
    _tpu_estimator_gauge = tf.compat.v2.__internal__.monitoring.BoolGauge(
AttributeError: module 'tensorflow._api.v2.compat.v2.__internal__' has no attribute 'monitoring'

**Comment by DanielTakeshi** [comment]
Thanks @k-makihara ! I think there might be something with TensorFlow here, maybe some version change? There was a similar issue but with a different error: https://github.com/DanielTakeshi/deformable-ravens/issues/4

Can you give the output of `conda list` in your conda environment?

**Comment by k-makihara** [comment]
Thank you for reply ! Now, I solved the problem by installing another version of python packages.
From settings of the install script(install_ubuntu.sh), I changed tensorflow-gpu version is 2.3.0 and automatically fit other packages to this by pip.
And some simulations could execute in my environment!
here show my package versions.

```
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main  
> _openmp_mutex             4.5                       1_gnu  
> absl-py                   0.14.1                   pypi_0    pypi
> astunparse                1.6.3                    pypi_0    pypi
> backcall                  0.2.0                    pypi_0    pypi
> ca-certificates           2021.7.5             h06a4308_1  
> cachetools                4.2.4                    pypi_0    pypi
> certifi                   2021.5.30        py37h06a4308_0  
> charset-normalizer        2.0.6                    pypi_0    pypi
> circle-fit                0.1.3                    pypi_0    pypi
> cycler                    0.10.0                   pypi_0    pypi
> decorator                 5.1.0                    pypi_0    pypi
> gast                      0.3.3                    pypi_0    pypi
> google-auth               1.35.0                   pypi_0    pypi
> google-auth-oauthlib      0.4.6                    pypi_0    pypi
> google-pasta              0.2.0                    pypi_0    pypi
> gputil                    1.4.0                    pypi_0    pypi
> grpcio                    1.41.0                   pypi_0    pypi
> h5py                      2.10.0                   pypi_0    pypi
> idna                      3.2                      pypi_0    pypi
> imageio                   2.9.0                    pypi_0    pypi
> importlib-metadata        4.8.1                    pypi_0    pypi
> ipython                   7.28.0                   pypi_0    pypi
> jedi                      0.18.0                   pypi_0    pypi
> keras-preprocessing       1.1.2                    pypi_0    pypi
> kiwisolver                1.3.2                    pypi_0    pypi
> ld_impl_linux-64          2.35.1               h7274673_9  
> libffi                    3.3                  he6710b0_2  
> libgcc-ng                 9.3.0               h5101ec6_17  
> libgomp                   9.3.0               h5101ec6_17  
> libstdcxx-ng              9.3.0               hd4cf53a_17  
> markdown                  3.3.4                    pypi_0    pypi
> matplotlib                3.4.3                    pypi_0    pypi
> matplotlib-inline         0.1.3                    pypi_0    pypi
> meshcat                   0.3.1                    pypi_0    pypi
> ncurses                   6.2                  he6710b0_1  
> networkx                  2.6.3                    pypi_0    pypi
> numpy                     1.18.5                   pypi_0    pypi
> oauthlib                  3.1.1                    pypi_0    pypi
> opencv-python             4.5.3.56                 pypi_0    pypi
> openssl                   1.1.1l               h7f8727e_0  
> opt-einsum                3.3.0                    pypi_0    pypi
> packaging                 21.0                     pypi_0    pypi
> parso                     0.8.2                    pypi_0    pypi
> pexpect                   4.8.0                    pypi_0    pypi
> pickleshare               0.7.5                    pypi_0    pypi
> pillow                    8.3.2                    pypi_0    pypi
> pip                       21.0.1           py37h06a4308_0  
> prompt-toolkit            3.0.20                   pypi_0    pypi
> protobuf                  3.18.0                   pypi_0    pypi
> ptyprocess                0.7.0                    pypi_0    pypi
> pyasn1                    0.4.8                    pypi_0    pypi
> pyasn1-modules            0.2.8                    pypi_0    pypi
> pybullet                  3.0.4                    pypi_0    pypi
> pygments                  2.10.0                   pypi_0    pypi
> pyngrok                   5.1.0                    pypi_0    pypi
> pyparsing                 2.4.7                    pypi_0    pypi
> python                    3.7.11               h12debd9_0  
> python-dateutil           2.8.2                    pypi_0    pypi
> pywavelets                1.1.1                    pypi_0    pypi
> pyyaml                    5.4.1                    pypi_0    pypi
> pyzmq                     22.3.0                   pypi_0    pypi
> ravens                    1.0.0                     dev_0    <develop>
> readline                  8.1                  h27cfd23_0  
> requests                  2.26.0                   pypi_0    pypi
> requests-oauthlib         1.3.0                    pypi_0    pypi
> rsa                       4.7.2                    pypi_0    pypi
> scikit-image              0.18.3                   pypi_0    pypi
> scipy                     1.4.1                    pypi_0    pypi
> setuptools                58.0.4           py37h06a4308_0  
> six                       1.16.0                   pypi_0    pypi
> sqlite                    3.36.0               hc218d9a_0  
> tensorboard               2.6.0                    pypi_0    pypi
> tensorboard-data-server   0.6.1                    pypi_0    pypi
> tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
> tensorflow-addons         0.14.0                   pypi_0    pypi
> tensorflow-estimator      2.3.0                    pypi_0    pypi
> tensorflow-gpu            2.3.0                    pypi_0    pypi
> tensorflow-hub            0.12.0                   pypi_0    pypi
> termcolor                 1.1.0                    pypi_0    pypi
> tifffile                  2021.8.30                pypi_0    pypi
> tk                        8.6.11               h1ccaba5_0  
> tornado                   6.1                      pypi_0    pypi
> traitlets                 5.1.0                    pypi_0    pypi
> transformations           2021.6.6                 pypi_0    pypi
> typeguard                 2.12.1                   pypi_0    pypi
> typing-extensions         3.10.0.2                 pypi_0    pypi
> u-msgpack-python          2.7.1                    pypi_0    pypi
> urllib3                   1.26.7                   pypi_0    pypi
> wcwidth                   0.2.5                    pypi_0    pypi
> werkzeug                  2.0.1                    pypi_0    pypi
> wheel                     0.37.0             pyhd3eb1b0_1  
> wrapt                     1.13.1                   pypi_0    pypi
> xz                        5.2.5                h7b6447c_0  
> zipp                      3.6.0                    pypi_0    pypi
> zlib                      1.2.11               h7b6447c_3  
```
